### ISSUE TITLE
Conceal angle brackets for links

### ISSUE THREAD

**Issue by musjj** [MDeiml/tree-sitter-markdown#100]
Angle brackets surrounding explicit links like:

```
<https://www.google.com>
```

Should be conceal-able

**Comment by MDeiml** [comment]
This should already be possible with the current state of the parser. The angle brackets are always the first and last character of the `uri_autolink` and `email_autolink` nodes. Are you using neovim? If so this probably requires writing some lua code, but I am not quite certain. I'd recommend opening an issue on https://github.com/nvim-treesitter/nvim-treesitter

**Comment by musjj** [comment]
I've realized that the concealing part is implemented within the neovim repo, thanks for the clarification.
