### ISSUE TITLE
Querying inlink_link nodes doesn't work.

### ISSUE THREAD

**Issue by peri4n** [MDeiml/tree-sitter-markdown#107]
Hi and first of all let me say thank you for your contributions.

This is not a bug or feature request. I just wanted to ask you a question and see if you have an idea how to solve it.
When I open the TreesitterPlayground inside Neovim and query for a node of type `indent_link` I don't get any results.

Looking at the injected languages I suspect it has something to do with the 2 parsers beeing used.

My ultimate goal is to create a key binding to jump to the next link using nvim-treesittes-textobjects.

**Comment by peri4n** [comment]
I managed to gain some insights on this:

Jumping to text object in the markdown_inline grammar only works when working when the filetype is set to markdown_inline.
Unfortunately, setting the ft to markdown_inline breaks the entire markdown setup.

I close this, as this is clearly not caused by the grammar.

**Comment by MDeiml** [comment]
Hey, sry I didn't answer in time. This is indeed not caused by the grammar. If you want to query nodes for the purpose of a plugin, you will have to iterate over all `markdown_inline` subtrees and query those for e.g. `indent_link`. Let me know if you need any help.
