### ISSUE TITLE
Nested list item parsed as indented code block when the uncle list item has a fenced code block

### ISSUE THREAD

**Issue by tomtomjhj** [MDeiml/tree-sitter-markdown#116]
**Describe the bug**
Nested list item is parsed as indented code block when the uncle list item has a fenced code block.

**Code example**

<pre>
* a
    * b
      ```
      c
      ```
    * d
        * e
</pre>

**Expected behavior**

The list item `* e` should be parsed as `list_item`. 

**Actual behavior**
It is parsed as `indented_code_block`. 

![image](https://github.com/MDeiml/tree-sitter-markdown/assets/19489738/f58c2776-1566-4294-815f-42b3bf9146ba)

In the following examples, `* e` is parsed as `list_item` as expected.
<pre>
* a
    * b
    * d
        * e
</pre>
<pre>
* b
  ```
  c
  ```
* d
    * e
</pre>

Environment:
* neovim HEAD (ac1c23442)
* the latest version of tree-sitter-markdown distributed by nvim-treesitter

**Comment by MDeiml** [comment]
Fixed it, thanks!
