### ISSUE TITLE
Disable underline for none-latin CJK letters.

### ISSUE THREAD

**Issue by Explorare** [MDeiml/tree-sitter-markdown#130]
**Environment**
Windows Terminal v1.19
Powershell v7.3.10
nvim v0.9.5
lazyvim latest

**Describe the bug**
All none-latin letters in markdown files are rendered with a underline, but rendered normally in .js file. Is there a way to change this behavior and remove the underlines for better readability?

**Code example**
```markdown
"The quick brown fox jumps over the lazy dog"
“敏捷的棕色狐狸跨过懒狗” mǐn jié de zōng sè hú lí kuà guò lǎn gǒu
ザ・クイック・ブラウン・フォックス・ジャンプス・オーバー・ザ・レイジー・ドッグ
「素早い茶色の狐はのろまな犬を飛び越える」
```

**Expected behavior**

![js](https://github.com/MDeiml/tree-sitter-markdown/assets/5090766/681b6835-f7e6-493b-a198-9aa9d116abfb)

**Actual behavior**
![md](https://github.com/MDeiml/tree-sitter-markdown/assets/5090766/794cd2cb-f49f-43b5-bcff-c3c4f0b68dbd)

**Comment by MDeiml** [comment]
I'm not quite sure what's happening there, it seems like some of the latin letters like the s in `sè`are also underlined. The syntax tree the parser produces doesn't contain anything that would cause the underline.

Maybe you have some spellcheck configured by accident? I think `:set nospell` should disable that if it's on. Does that remove the underlines?

**Comment by Explorare** [comment]
That's it, `:set nospell` fix the problem. Thank you for your help : )
