### ISSUE TITLE
Transfer parser to tree-sitter-grammars org?

### ISSUE THREAD

**Issue by clason** [MDeiml/tree-sitter-markdown#133]
*(Reposting from [here](https://github.com/MDeiml/tree-sitter-markdown/pull/108#issuecomment-1941115641) for better visibility)*

Hi @MDeiml 👋 

Recently, some tree-sitter and nvim-treesitter maintainers have gotten together and created a https://github.com/tree-sitter-grammars as a home for stable but not "official" (tree-sitter org) parsers. The goal is to help out with and automate routine maintenance (testing, releases, adaptation to upcoming large changes in tree-sitter itself); you can see the (work in progress) at https://github.com/tree-sitter-grammars/template.

As you mentioned you're low on time currently (and this is one of the most important parsers at least for Neovim), I'd like to offer a good home and additional hands-on-deck ;) Would you consider transferring your parser to the org? You'd keep write access (but not admin, unless there's a strong special reason), of course.

If you do, the simplest way is just transfer the org to @amaanq, @lewis6991, or me, and we'll transfer to the org. (Direct transfers to organizations are a bit difficult with Github.) If you have questions or concerns, let me know.

**Comment by MDeiml** [comment]
Ah im sorry, was quite busy this week and didn't want to do this in a rush. I'll have a look at it in an hour or so, but the project sounds like a good idea.

**Comment by clason** [comment]
No worries, just wanted to make sure you saw the offer. (It's also something that can be reversed at a later time.)

**Comment by MDeiml** [comment]
Transferred it to you :+1:

**Comment by clason** [comment]
Great, transfer complete! Welcome to the family!
