### ISSUE TITLE
Table support?

### ISSUE THREAD

**Issue by ibhagwan** [MDeiml/tree-sitter-markdown#15]
First, great job on this and ty for taking ownership on mardown in neovim treesitter :-)

Are tables supported? I'm using treesitter to auto-generate vimdoc for  my plugin from the README, I used to do with https://github.com/ikatyang/tree-sitter-markdown which recognized the below as table, this seems not to be the case here.

Are tables supported?

![screenshot-1639535526](https://user-images.githubusercontent.com/59988195/146112435-feb97ec5-d8da-4aba-a342-19444be03f4b.png)

For reference, here's how it's parsed with the ikatyang:
![screenshot-1639536128](https://user-images.githubusercontent.com/59988195/146113415-dd1cb217-e469-4ab0-bb0a-a9420debedf5.png)

**Comment by MDeiml** [comment]
Tables are part of [Github flavored markdown](https://github.github.com/gfm/) which is an extension of the CommonMark spec. I plan to add support for Github flavored markdown including tables, but so far haven't gotten around to it.

**Comment by ibhagwan** [comment]
Tysm, looking forward to it!

**Comment by ibhagwan** [comment]
FYI, I updaed [my fork of `babelfish.nvim`](https://github.com/ibhagwan/babelfish.nvim) to work against your new parser, code is ugly as hell with a couple of hacks to support tables and other minor adjustments (TBH, the original code wasn't all that great to begin with) but it does work, and it does produce a fantastic result for my plugin's vimdoc, in case you wanna check it out:

[README](https://github.com/ibhagwan/fzf-lua/blob/main/README.md)
[vimdoc](https://github.com/ibhagwan/fzf-lua/blob/main/doc/fzf-lua.txt)

**Comment by MDeiml** [comment]
That looks great. I hope I will get to tables soon so the official repo for babelfish can use this parser. But I think I won't get too much done over Christmas

**Comment by MDeiml** [comment]
Should work with the newest commit :tada:
