### ISSUE TITLE
Is this package pip installable?

### ISSUE THREAD

**Issue by TACIXAT** [MDeiml/tree-sitter-markdown#156]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

I am upgrade to version 22 and modules can no longer be built using `build_library`. Does this repo have a `pip` package?

### Describe the solution you'd like

`pip install tree-sitter-markdown`

`pip install tree-sitter-markdown-inline`

### Describe alternatives you've considered

Alternatively, will a local `pip install` of the repo work?

**Comment by ObserverOfTime** [comment]
```bash
pip install git+https://github.com/tree-sitter-grammars/tree-sitter-markdown
```
Until a package is published.
