### ISSUE TITLE
Link concealing?

### ISSUE THREAD

**Issue by smartding** [MDeiml/tree-sitter-markdown#16]
I've been using plasticboy/vim-markdown for markdown syntax highlighting and other stuff for years.
I really misses the link concealing feature of that plugin when I switched to tree-sitter-markdown today.
Link concealing shows `[text](link)` as **text** and make the whole document less cluttered, especially if the link is very long.

Not sure if link concealing is within the scope of tree-sitter.

**Comment by MDeiml** [comment]
You could try `additional_vim_regex_highlighting = true` as documented [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/d2174f1d29086b51124d084f9402c5f9731f21bd/doc/nvim-treesitter.txt#L130). But that's just a workaround that enables the traditional vim syntax in the background, so you will get no performance benefit from using tree-sitter.

**Comment by smartding** [comment]
Ok, thanks.

**Comment by Liverm0r** [comment]
so have you achieve concealing? I tried additional_vim_regex_hightlighting and it doesn't work for me

**Comment by smartding** [comment]
@Liverm0r 
No, I went back to plasticboy/vim-markdown. Because I need link concealing, and I can live with the not-so-good performance.

**Comment by Liverm0r** [comment]
By the way, before treesitter and lsp I was using [vim-polyglot](https://github.com/sheerun/vim-polyglot), and it was also concealing .md links.
