### ISSUE TITLE
bug: incremental_selection at ending space reports E5108

### ISSUE THREAD

**Issue by xudyang1** [MDeiml/tree-sitter-markdown#167]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [x] I have searched the existing issues

### Describe the bug

When cursor is at the end of a line with a space, calling incremental selection in markdown file throws E5108.

### Steps To Reproduce/Bad Parse Tree

1. `nvim repro.md`
2. type `ahello world`, with an extra space at the end
3. exit insert mode, move cursor to the ending space and use keymap to call `node_incremental`
4. Error message is shown:

```text
E5108: Error executing lua: ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: attempt to index local 'node_or_range' (a n
il value)
stack traceback:
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: in function 'get_node_range'
        ...im/lazy/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:279: in function 'update_selection'
        ...treesitter/lua/nvim-treesitter/incremental_selection.lua:19: in function <...treesitter/lua/nvim-treesitter/incremental_selec
tion.lua:15>
```

### Expected Behavior/Parse Tree

Parse the node correctly

**Comment by xudyang1** [comment]
Here is what I tried in neovim:

Adding the following lines in `nvim-treesitter/lua/nvim-treesitter/ts_utils.lua`, line 207:
```lua
vim.print("ts.is_in_node_range(root, line, col):", ts.is_in_node_range(root, line, col))
vim.print("root:range(): ", root:range())
vim.print("range: {line, col, line, col+1}", { line, col, line, col + 1 })
```

1. repro.md with "hello " (one extra space, error occurs)
```text
ts.is_in_node_range(root, line, col):
false
root:range():
0
0
0
5
range: {line, col, line, col+1}
{ 0, 5, 0, 6 }
E5108: Error executing lua: ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: attempt to index local 'node_or_range' (a n
il value)
stack traceback:
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: in function 'get_node_range'
        ...im/lazy/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:283: in function 'update_selection'
        ...treesitter/lua/nvim-treesitter/incremental_selection.lua:19: in function <...treesitter/lua/nvim-treesitter/incremental_selec
tion.lua:15>
```

2. repro.md with "hello  " (two extra spaces, works)
```text
root:
<userdata 1>
ts.is_in_node_range(root, line, col):
true
root:range():
0
0
1
0
range: {line, col, line, col+1}
{ 0, 6, 0, 7 }
```
3. repro.py (or repro.any_file_type) with "hello " (one extra space, works)
```text
root:
<userdata 1>
ts.is_in_node_range(root, line, col):
true
root:range():
0
0
1
0
range: {line, col, line, col+1}
{ 0, 5, 0, 6 }
```

So, I guess tree-sitter-markdown produces a wrong `root:range()` when cursor is at the extra ending space (should be 0 0 1 0 instead of 0 0 0 5).

**Comment by MDeiml** [comment]
I would guess that this is most likely a neovim specific issue. In that case it would be best to report it at https://github.com/nvim-treesitter/nvim-treesitter.

**Comment by xudyang1** [comment]
Closed, reported to [neovim](https://github.com/neovim/neovim/issues/31015)

**Comment by xudyang1** [comment]
Ending space is not included in `$.inline` https://github.com/neovim/neovim/issues/31015#issuecomment-2450416154

**Comment by MDeiml** [comment]
I still don't think the parser is at fault here. It produces a syntax tree without throwing an error, and `node_incremental` as I understand should work irrespective of the semantic meaning of that syntax tree.

I can test if changing the `inline` node like you suggest fixes the issue though.

**Comment by MDeiml** [comment]
I added a new branch, where the final space should now be contained in the `inline` node, could you check if this helps?
https://github.com/tree-sitter-grammars/tree-sitter-markdown/tree/paragraph_inline_with_space

**Comment by xudyang1** [comment]
> I added a new branch, where the final space should now be contained in the `inline` node, could you check if this helps? https://github.com/tree-sitter-grammars/tree-sitter-markdown/tree/paragraph_inline_with_space

The `paragraph_inline_with_space` branch works. I also replace `markdown.so` and `markdown_inline.so` in neovim's parser directory, running `nvim --clean repro.md` also works as expected. 

```text
(document [0, 0] - [1, 0]
  (section [0, 0] - [1, 0]
    (paragraph [0, 0] - [1, 0]
      (inline [0, 0] - [1, 0]))))
```

I tested it with `tree-sitter test` in `tree-sitter-markdown` subdirectory, and many examples failed with:

```text
                  (inline                                            // unexpected
                    (block_continuation))))                // unexpected
                  (inline)                                           // expected
                  (block_continuation)))                   // expected
```

I believe those are false positive as the `paragraph` rule was changed.

Thank you for your hard work on it. Closing this.
