### ISSUE TITLE
Titles not detected after an empty inner list item (bullet point)

### ISSUE THREAD

**Issue by jaekyeom** [MDeiml/tree-sitter-markdown#17]
I think titles after an empty inner list item are not detected.
Here is some example:
![image](https://user-images.githubusercontent.com/6262727/146156208-26b85843-b748-4142-8ab5-b887c34f4392.png)

Thank you!

**Comment by MDeiml** [comment]
Minimal test case
```markdown
* a
  * b
  *


# C
```
