### ISSUE TITLE
bug: link_destinations with spaces do not get parsed

### ISSUE THREAD

**Issue by erikli** [MDeiml/tree-sitter-markdown#173]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [x] I have searched the existing issues

### Describe the bug

Image paths with spaces do not get recognized as `link_destinations`

### Steps To Reproduce/Bad Parse Tree

Markdown file:

```
![](./image1.png)

![](./image 2.png)
```

Parses as

```
section [0, 0] - [3, 0]
  paragraph [0, 0] - [1, 0]
    inline [0, 0] - [0, 17]
      image [0, 0] - [0, 17]
        link_destination [0, 4] - [0, 16]
  paragraph [2, 0] - [3, 0]
    inline [2, 0] - [2, 18]
```

![Image](https://github.com/user-attachments/assets/acb44881-d346-455d-a41b-dcd478eb0017)

### Expected Behavior/Parse Tree

I expect the second link with a space to still parse. Is this not valid markdown?

**Comment by tbung** [comment]
Hey, spaces in links like this are indeed not valid markdown, you would need to enclose the file name (or url or whatever your link destination is) in `<...>`. To quote the [spec](https://spec.commonmark.org/0.30/#link-destination):
> A [link destination](https://spec.commonmark.org/0.30/#link-destination) consists of either
> - a sequence of zero or more characters between an opening < and a closing > that contains no line endings or unescaped < or > characters, or
> - a nonempty sequence of characters that does not start with <, does not include [ASCII control characters](https://spec.commonmark.org/0.30/#ascii-control-character) or [space](https://spec.commonmark.org/0.30/#space) character, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

While links with spaces in `<>` indeed get parsed, the parsed url includes the angle braces so the nvim key combos `gf` and `gx` still have issues with that. See #174 .

**Comment by erikli** [comment]
Thanks so much for the explanation! I will close this as WONTFIX since it seems like it was my error in understanding the Markdown spec, and issue 174 is already dealing with the functionality question for `gf`/`gx`
