### ISSUE TITLE
List markers highlight?

### ISSUE THREAD

**Issue by LamprosPitsillos** [MDeiml/tree-sitter-markdown#19]
Is there a way for the list markers to get some highlighting? Thanks!

**Comment by kofm** [comment]
It depends on your editor and colorscheme, list markers are correctly parsed at the moment like e.g. (list_marker_minus) or (list_marker_star).
In nvim-treesitter e.g. query highlights are like this:
```
[
  (list_marker_plus)
  (list_marker_minus)
  (list_marker_star)
  (list_marker_dot)
  (list_marker_parenthesis)
  (thematic_break)
] @punctuation.special
```
It is then the job of your colorscheme to define highlight
If you're on neovim you can use [colorbuddy](https://github.com/tjdevries/colorbuddy.nvim) to easily define one

I suggest you to take a look at [Treesitter](https://tree-sitter.github.io/tree-sitter/) website to understand how this work.

**Comment by MDeiml** [comment]
This is correct. I hope it answered your question? If not feel free to ask.
