### ISSUE TITLE
missing case for `[TIGHT|LOOSE]_LIST_ITEM + 3`?

### ISSUE THREAD

**Issue by dimbleby** [MDeiml/tree-sitter-markdown#2]
A random thing I noticed while looking over the code the other day: the cases for list_item + 3 seem to be missing from https://github.com/MDeiml/tree-sitter-markdown/blob/921ce062919d356ebf424eddc709cd2182e7b903/src/scanner.cc#L194-L201 

Possibly there's something clever going on and this case is indeed special and deliberately missing; but it looks like it might be an accident!

**Comment by MDeiml** [comment]
Oh, you're right. Thanks for catching that.
