### ISSUE TITLE
Highlight group suggestions

### ISSUE THREAD

**Issue by pwntester** [MDeiml/tree-sitter-markdown#20]
Thanks for the awesome parser!

I have some suggestions that could improve the highlighting:

- [quote symbol (`>`)](https://commonmark.org/help/tutorial/05-blockquotes.html) should have `TSPunctSpecial` highlight group
- [fenced code block symbol (backtick) and language](https://commonmark.org/help/tutorial/09-code.html) are currently using `TSLiteral` group, I think it would be better to use `TSPunctDelimiter`
- [link delimiters (`[]()`)](https://commonmark.org/help/tutorial/07-links.html) should use `TSPunctDelimiter` or `TSPunctBracket` highlight group
- [Emphasis characters (`_` and `*`)](https://commonmark.org/help/tutorial/02-emphasis.html) should use `TSPunctDelimiter` highlight group

Thanks again!

**Comment by pwntester** [comment]
Oh, just figured out this issue belongs to nvim-treesitter, not here. Thanks again!

**Comment by pwntester** [comment]
Looking at the parsed elements, I miss:
- the quote marker (similar to `list_marker_minus`)
- the emphasis markers
- fenced code block delimiters markers

I feel like at least the first two should have their own elements. Is it possible to add them?

**Comment by MDeiml** [comment]
Good suggestions. For the fenced code block delimiters a current work around would be to set the whole code block to be `TSPunctDelimiter` and setting the content to be `TSLiteral`. The other two need extra nodes, I think it would also maybe be nicer to add nodes for the fenced code block delimiters as well.

**Comment by David-Else** [comment]
Hi, I am trying to add the right highlights to a theme for Treesitter and Markdown and wondered if anyone could advise me which to use for the following?
```
# (< the actual #) Heading
# (< the actual #) Heading
# (< the actual #) Heading

**Comment by David-Else** [comment]
Hi, I am trying to add the right highlights to a theme for Treesitter and wondered if anyone could advise me which to use for the following **bold** parts of the text? (they won't all render bold on GitHub, so I stuck them in a code block)
```
**#** Heading 1
**##** Heading 2
**###** Heading 3

**-** unordered list
**-** unordered list

**1.** ordered list
**2.** ordered list

!(**image**)[url]

**>** note
```
The details of the colors with screenshots are at: https://github.com/Mofiqul/vscode.nvim/pull/30

**Comment by MDeiml** [comment]
The `highlights.scm` from this repository does not work with what you want to do, but you could easily write your own queries. If you're not familiar with tree-sitter queries you can look at the tree-sitter documentation for syntax highlighting.

With that said
* The markers for headings are called `atx_h1_marker`, `atx_h2_marker` ...
* The list markers are called `list_marker_minus`, `list_marker_plus` and `list_marker_star` for unordered lists and `list_marker_dot` and `list_marker_parenthesis` for ordered lists.
* The image example you supplied is not valid syntax and should actually be `![**image**](url)` but you are probably looking for `image_description`.
* The `>` can actually not be individually highlighted yet, that is part of this issue

**Comment by pwntester** [comment]
For now, I submitted this [PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/2174/files) to highlight link delimiters and frontmatter

**Comment by MDeiml** [comment]
Everything discussed here should be implemented now as far as I know (for now the closing `)` are deactivated in nvim-treesitter because of an internal problem, see https://github.com/nvim-treesitter/nvim-treesitter/issues/2206).
