### ISSUE TITLE
Code fence indents

### ISSUE THREAD

**Issue by axieax** [MDeiml/tree-sitter-markdown#21]
Hi, not too sure about the current implementation, but would it be possible to get treesitter indenting according to the parser for the language corresponding to code blocks, just like how treesitter highlights are correctly used based on the language?

**Comment by MDeiml** [comment]
I imagine you are using nvim-treesitter? I think this would require a `indentation.scm` query file, but I am not an expert on this. I think it would make more sense to open an issue on the nvim-treesitter repo.
