### ISSUE TITLE
How to enable that for rmarkdown?

### ISSUE THREAD

**Issue by fecet** [MDeiml/tree-sitter-markdown#22]

**Comment by BlackEdder** [comment]
I would also be interested in this, but note that rmarkdown uses ```{r, ....} for code blocks, which is different from normal markdown and caused many errors when I tested this plugin on rmarkdown some time ago.

**Comment by fecet** [comment]
> I would also be interested in this, but note that rmarkdown uses ```{r, ....} for code blocks, which is different from normal markdown and caused many errors when I tested this plugin on rmarkdown some time ago.

I'm aware there would be many errors, but I should make rmd use the Markdown parser firstly.  Is
```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.markdown.used_by = { "rmd","markdown","pandoc","rmarkdown" }
```
the right way for this?

**Comment by kofm** [comment]
This is the repo for the treesitter markdown parser. Treesitter is not specifically bound to neovim, in fact, is the other way around. Neovim, as other text editor and software use treesitter to parse code and provide features such as highlighting and so on. 

You should really ask this in https://github.com/nvim-treesitter/nvim-treesitter
Spoiler alert: there's currently no support for rmarkdown. I'm also interested and trying to implement this myself by forking this repo but atm i'm still trying to figure out how treesitter work (it's probably far beyond my programming skills)
See here: https://github.com/nvim-treesitter/nvim-treesitter/issues/529

**Comment by MDeiml** [comment]
> the right way for this?

That should be the right way, but if it does not work you should probably ask in the nvim-treesitter repo as @kofm suggested

It is also true that this markdown grammar is for the CommonMark / Github flavor of markdown specifically, so rmarkdown is not completely (and probably never will) supported by this repo, but it should be a good starting point. For this to truly work well with rmarkdown you would probably have to fork it and implement the R specific parts yourself.

Also sadly treesitter does not have any good way to support multiple different but similar syntaxes in one grammar, so there's no nice way around maintaining two different versions. But by using git branches / forks it should be possible to avoid doing double the work.

> I would also be interested in this, but note that rmarkdown uses ```{r, ....} for code blocks, which is different from normal markdown and caused many errors when I tested this plugin on rmarkdown some time ago.

This problem is known and I opened a pull request on nvim-treesitter to fix it, should be better as soon as that is merged

**Comment by David-Else** [comment]
Pandoc uses the following format for some of its Lua plugins, and it seems to make Neovim crash and slow down:

`example.md`
````md


```{.include}
file-a.md
```

```{.include shift-heading-level-by=1}
file-a.md
```
````
Is this type of markdown addition supported? https://github.com/pandoc/lua-filters/blob/master/include-files/README.md

**Comment by MDeiml** [comment]
I'm not aware of any recent fix. I would think this has to do with an error with neovim itself, specifically adressed in this PR: https://github.com/neovim/neovim/pull/16668

The pandoc syntax is not supported per se, but still should produce some sensible highlighting, as there probably is no installed grammar for the language `{.include}`.

**Comment by MDeiml** [comment]
I'm closing this issue for now. rmarkdown will never be supported 100% (at least in the main branch) as I said. But please anyone message me if you fork this for rmarkdown / are interested in implementing this.

**Comment by aspeddro** [comment]
A full parser for rmarkdown will be possible when a parser for pandoc is implemented. RMarkdown is actually based on pandoc which is an extension of GFM. Therefore a parser for rmarkdown must be forked from a parser for pandoc.

[Pandoc Extensions](https://pandoc.org/MANUAL.html#extensions)
