### ISSUE TITLE
Code fense aliases

### ISSUE THREAD

**Issue by sarmong** [MDeiml/tree-sitter-markdown#24]
Tim Pop's [implementation](https://github.com/tpope/vim-markdown) includes the following
```
let g:markdown_fenced_languages = ['bash=sh']
```

It would be nice to implement in here as well.

**Comment by MDeiml** [comment]
This repo is just for the tree-sitter markdown grammar, which is not actually specific for neovim. You could ask in the nvim-treesitter repo for any neovim specific questions.

Searching about this I came up with this https://github.com/nvim-treesitter/nvim-treesitter/issues/812 which seems to be at least similar to what you want to do.
