### ISSUE TITLE
Is there any way that I can get the conceal math in Markdown?

### ISSUE THREAD

**Issue by AndOrangutan** [MDeiml/tree-sitter-markdown#30]
Grettings,
I have been working on getting my notetaking setup for my classes and love having some sort of plugin to do math conceal. As you can see even though I have [preservim/vim-markdown](https://github.com/preservim/vim-markdown) installed but the conceal doesn't work with Treesitter.

With TS enabled:
![2022-01-24_11-49](https://user-images.githubusercontent.com/40435989/150853996-2b8a49ba-a3cb-43e9-85ac-a8ed2e3cb830.png)

With TS Disabled:
![2022-01-24_11-49_1](https://user-images.githubusercontent.com/40435989/150854058-0a037c86-afca-4ef6-a03b-7570244b8f2f.png)

**Comment by MDeiml** [comment]
You could try adding this to your config (from nvim-treesitters help):
```lua
  lua <<EOF
  require'nvim-treesitter.configs'.setup {
    highlight = {
      -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
      -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
      -- Using this option may slow down your editor, and you may see some duplicate highlights.
      -- Instead of true it can also be a list of languages
      additional_vim_regex_highlighting = false,
    },
  }
  EOF
```

**Comment by AndOrangutan** [comment]
Thank you so much. :D

**Comment by megalithic** [comment]
> ```lua
>       additional_vim_regex_highlighting = false,
> ```

curious @MDeiml ; can this boolean be set on a per-lang basis? or is it all-or-nothing?

**Comment by MDeiml** [comment]
It says in the nvim-treesitter docs that it can be a list of languages, so `{ 'markdown' }` in this case
