### ISSUE TITLE
Feature request: add front matter support

### ISSUE THREAD

**Issue by ikalnytskyi** [MDeiml/tree-sitter-markdown#32]
## Rationale

Markdown is a quite popular choice for writing content for static sites or documentation. Majority of existing tooling supports so called "front matter" that allows to attach some metadata to the document. 

See example https://gohugo.io/content-management/front-matter/

## Suggestion

Front matter is neither a part of the standard nor standardize among existing tooling. Nevertheless, it seems community pretty much settled on two front matter formats:

* YAML is used in case of `---` separator. E.g:

  ```markdown
  ---
  tags: [foo, bar]
  summary: a short summary
  ---

  # My blog post
  
  ...
  ```

* TOML is used in case of `+++` separator. E.g:

  ```markdown
  +++
  tags = ["foo", "bar"]
  summary = "a short summary"
  +++

  # My blog post
  
  ...
  ```

It would be nice to support both YAML and TOML injections for this 2 most popular choices. I'm sure it would cover 99% of cases.

**Comment by MDeiml** [comment]
In nvim-treesitter this is done by querying content between two consecutive thematic breaks, but this is of course not very accurate and stable. So this seems like a good idea.

**Comment by MDeiml** [comment]
Yes kind of. In realtiy it checks for thematic breaks, so it doesn't work to great. You can see the query in nvim-treesitter [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/6e293230071cbdc8bb13931f8fc4739dc389fec2/queries/markdown/injections.scm#L9). To use this you may need to update nvim-treesitter of course.

**Comment by mhanberg** [comment]
I have noticed that the neovim treesitter query works if there is an extra space at the end of the frontmatter. here is an example 

https://user-images.githubusercontent.com/5523984/156380005-4f38dbb9-9a34-4ec3-98ae-d8b81af8f72e.mov

**Comment by MDeiml** [comment]
This is implemented in the newest version. (Update the nvim-treesitter plugin and run `:TSUpdate` to get the newest version)

**Comment by MDeiml** [comment]
Currently both pluses and minuses cause the content to be parsed as YAML as that is the behavior. I'm not sure why, probably because I made a mistake writing the query.

It's easy to fix with `:TSEditQueryUserAfter injections markdown` though and someone motivated could open a PR to nvim-treesitter
