### ISSUE TITLE
nvim becomes unresponsive when a fenced code block uses attributes

### ISSUE THREAD

**Issue by jmbuhr** [MDeiml/tree-sitter-markdown#33]
Hi there and thank you for your parser! Fixing this issue might be out of scope, as it is specific to `pandoc`s extension of markdown, but since it leads to a crash / nvim becoming unresponsive I am reporting it anyways because people might come across this by accident.

Pandoc allows attributes to be added to block level and inline elements (https://pandoc.org/MANUAL.html#extension-attributes) using a syntax with curly braces (https://pandoc.org/MANUAL.html#extension-header_attributes). These attributes can also be added to (fenced) code blocks (https://pandoc.org/MANUAL.html#fenced-code-blocks), which is commonly used by literate programming formats combining computation and documentation such as Rmarkdown to note down the language of a code block for execution. Unfortunately this syntax leads to a crash.

So while

````
```R
1 + 1
```
````
works,
````
```{R}
1 + 1
```
````
becomes very slow once it is typed out and gives warnings about the missing closing `}` while typing. This must be somehow related to how the `info_string` after the three backticks is parsed. If this could allow for curly braces it would help a lot of pandoc and Rmarkdown users.

**Comment by MDeiml** [comment]
I already tried to solve this problem in https://github.com/nvim-treesitter/nvim-treesitter/pull/2125. Are you sure you are using the most recent version of this parser? I'll have a look at this later.

**Comment by jmbuhr** [comment]
Thanks for looking into this. Yes, I updated and re-installed through nvim-treesitter (should this get the latest version?)

**Comment by jmbuhr** [comment]
So it looks like the according to https://github.github.com/gfm/#example-113 the info string can essentially be anything, where the first word is typically used as the language of the code block. I assume this breaks when this language part starts with a curly brace due to some language lookup? Curly braces in other places don't cause the lag.

````
```R {hello}
1 + 1
```
````

It is not part of the spec, but would be amazing for Rmarkdown users, if the whole info string could optionally be surrounded by curly braces :)

**Comment by jmbuhr** [comment]
Hm, from a pandoc markdown point of view it would be the most encompassing solution if curly braces following an element would be parsed as a space separated list of arguments (arguments can be keys or key-value pairs, see https://pandoc.org/MANUAL.html#extension-attributes) and if a code block has no info_string, but one of those lists instead, the first argument would be used as the language. I would be totally fine if you say this strays to far from the commonmark specification (though it is an extension which does not break existing rules) and should live in a separate fork, but it would certainly be cool.

**Comment by MDeiml** [comment]
CommonMark doesn't actually specify to strictly what part of the info string should be interpreted as the language, so I'm fine with this. Also I don't think there is any case where the braces should be part of the language. So I agree with you there.

**Comment by MDeiml** [comment]
This should be fixed now, but it's gonna take some time until the version lockfile in nvim-treesitter is automatically updated. If this is urgent to you, you could manually install the newest version. Also feel free to reopen this if there are more issues with pandoc style fenced code block attributes.
