### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Tiggilyboo** [MDeiml/tree-sitter-markdown#34]
Hello!

If possible could you publish the rust crate to [crates.io](https://crates.io/) so that it can be consumed by other rust crates?

Cheers!

**Comment by MDeiml** [comment]
There already is a `tree-sitter-markdown` crate. Any suggestions on what to name this crate?

**Comment by ghishadow** [comment]
> There already is a tree-sitter-markdown crate. Any suggestions on what to name this crate?

`tree-sitter-md`

**Comment by MDeiml** [comment]
Done! Feel free to reopen if you think I messed sth up. This is the first crate I published.
