### ISSUE TITLE
comma in info string prevents language specific parsing of code block

### ISSUE THREAD

**Issue by fisher-j** [MDeiml/tree-sitter-markdown#38]
I really appreciate code parsing in fenced code blocks. In Rmarkdown, the language identifier (`r`) is often followed by a comma and further "chunk options". The comma prevents the language from being recognized. Could we allow comma in addition to whitespace after language identifier?

    ```{r, fig.height=4, fig.width=7}
    x <- rnorm(100)                  # no syntax highlighting in these blocks
    plot(x)
    ```

    ```{r chunk-name, fig.height=4, fig.width=7}
    x <- rnorm(100)                  # this block has proper highlighting
    plot(x)
    ```

**Comment by jmbuhr** [comment]
Until this is possible, you can use the the new way of specifying chunk options via the `#|` comment (https://yihui.org/knitr/options/#chunk-options , https://quarto.org/docs/computations/r.html)
