### ISSUE TITLE
Proposal: `link_text` match only content

### ISSUE THREAD

**Issue by aspeddro** [MDeiml/tree-sitter-markdown#4]
@MDeiml great job. I'm using it on neovim.

`link_text` include `[` and `]`, should only capture the content, like `link_destination`?

![image](https://user-images.githubusercontent.com/16160544/144159090-a891d75d-49f6-4cd4-9443-cafc8d6df081.png)

**Comment by MDeiml** [comment]
I agree. I initially just implemented it like this because it's closer to the spec.
