### ISSUE TITLE
Add support for c++ as a valid language identifier along with cpp

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [MDeiml/tree-sitter-markdown#40]
Currently in a md file, these is what the cplusplus code blocks look like:

<img width="454" alt="Screenshot 2022-06-11 at 7 29 32 PM" src="https://user-images.githubusercontent.com/90276965/173191027-c72b9f30-4bec-4073-841e-e96f3244238e.png">

Some projects use `c++` instead of `cpp` to mark cplusplus code blocks, it would be nice if that was recognised as well.
I would've made a PR, but I am not well acquainted with the ways of tree-sitter, hence filing an issue.

Thanks!

**Comment by MDeiml** [comment]
I assume you are using neovim? This issue should better be discussed in the nvim-treesitter repo. The tree-sitter-markdown grammar just marks all the elements of the markdown file. It can't actually change how languages are injected. nvim-treesitter does the actual work for that, so feel free to open an issue there.

**Comment by Kiran-Raj-Dev** [comment]
Oh sorry, thanks for pointing me in the right direction!
