### ISSUE TITLE
block_quote_marker includes whitespace

### ISSUE THREAD

**Issue by Galicarnax** [MDeiml/tree-sitter-markdown#41]
I've played around with Treesitter playground (using Neovim), with the aim to have nice-looking markdown right in the nvim buffer (using `conceal`). I found that the `block_quote_marker` nodes include not only `>` but also the next whitespace. Is this dictated by Markdown syntax? If so, is it possible to break down them into two nodes?

**Comment by MDeiml** [comment]
There is some syntactical relevance to this. E.g. which of the whitespaces should be part of the actual text content. But I think at the point the output is less than perfect.

I'm currently restructuring the whole parser, so I probably won't be able to improve this now, but I'll keep it in mind for the future.

**Comment by GnikDroy** [comment]
I'm sure you are already aware of this but this also applies to heading markers, list markers and so on.

**Comment by petobens** [comment]
@MDeiml  @GnikDroy  so this is the reason why if I try to conceal a list marker like:
```
((list_marker_minus) @punctuation.special.list_minus.conceal (#set! conceal "•"))
```
then I get no space between the symbol and the text?:
![image](https://github.com/MDeiml/tree-sitter-markdown/assets/2583971/5cba2e61-b74a-4295-b188-32c2084b688f)

Is there any current way of avoiding this? (i.e a workaround)?

**Comment by MDeiml** [comment]
@petobens the list marker should always be followed by a whitespace, so setting
```
((list_marker_minus) @punctuation.special.list_minus.conceal (#set! conceal "• "))
```
(note the extra space after the bullet point) should fix this for you

**Comment by MDeiml** [comment]
#119 actually fixed this for atx headings

**Comment by petobens** [comment]
Hi @MDeiml thanks your your reply. Unfortunately your solution of adding a space after the bullet point doesn't work:

![image](https://github.com/MDeiml/tree-sitter-markdown/assets/2583971/d6d621ff-67a7-4f09-8670-ce04a7d10b47)

> https://github.com/MDeiml/tree-sitter-markdown/pull/119 actually fixed this for atx headings

So are you planning to add this the same fix for `list_items`?

**Comment by clason** [comment]
> @petobens the list marker should always be followed by a whitespace, so setting
> 
> ```
> ((list_marker_minus) @punctuation.special.list_minus.conceal (#set! conceal "• "))
> ```
> 
> (note the extra space after the bullet point) should fix this for you

Unfortunately, this doesn't work -- (Neo)Vim only allows specifying a single character to replace a conceal. (But changing this is on the roadmap.)

**Comment by petobens** [comment]
@clason so there are basically two options? i) wait for nvim to allow for more than one character in conceal symbols or ii) make a change to the markdown parser to avoid capturing the whitespace in list items similar to #119?

**Comment by clason** [comment]
As far as I can see (and option (i) is long-term; that's a lot of work).

**Comment by ribru17** [comment]
@Galicarnax I've found this to be a basically perfect solution for the block quote conceals:
```scheme
; Block quotes
((block_quote_marker) @punctuation.special
                      (#offset! @punctuation.special 0 0 0 -1)
                      (#set! conceal "▐"))
((block_continuation) @punctuation.special
                      (#eq? @punctuation.special ">")
                      (#set! conceal "▐"))
((block_continuation) @punctuation.special
                      (#eq? @punctuation.special "> ")
                      (#offset! @punctuation.special 0 0 0 -1)
                      (#set! conceal "▐"))
((block_continuation) @punctuation.special
                      ; for indented code blocks
                      (#eq? @punctuation.special ">     ")
                      (#offset! @punctuation.special 0 0 0 -5)
                      (#set! conceal "▐"))
```

it will conceal markers always, regardless of nesting level of markers themselves and their content.

**Comment by ribru17** [comment]
@petobens A workaround for the bullets that I use is the following:
```scheme
([(list_marker_minus) (list_marker_star)] @punctuation.special
  (#offset! @punctuation.special 0 0 0 -1) (#set! conceal "•"))
```
by setting an `offset` you can fix the spacing issue.

**Comment by petobens** [comment]
@ribru17 awesome! Exactly what I needed. Thank you!!!

**Comment by MDeiml** [comment]
I looked into this and sadly it seems implementing this would require quite some code changes (because of complex interactions between the spaces after a list marker and indented code blocks). So this will probably not be implemented any time soon.

That said the workaround by @ribru17 should work perfectly.

**Comment by clason** [comment]
Feel free to make a PR to nvim-treesitter.

**Comment by ribru17** [comment]
> Feel free to make a PR to nvim-treesitter.

Sorry, was this in reference to the conceal solutions above or were you talking to someone else?

**Comment by clason** [comment]
> > Feel free to make a PR to nvim-treesitter.
> 
> 
> 
> Sorry, was this in reference to the conceal solutions above or were you talking to someone else?

Yes, exactly.
