### ISSUE TITLE
Segfault in neovim on roc FAQ.md

### ISSUE THREAD

**Issue by kyazdani42** [MDeiml/tree-sitter-markdown#44]
Hi ! First thanks a lot for maintaining this markdown parser :)

Neovim crashes with a segfault when opening the FAQ.md file in the source code from roc lang (https://www.roc-lang.org/), and i believe it's related to the markdown parser, but i'm not a 100% sure because it could be related to some other parser that is injected.

I can take a look when i have some time during this week if you wish.

**Comment by MDeiml** [comment]
The file doesn't produce any segfaults when I use it with this parser outside of neovim. Maybe this is a problem with the elm parser?

**Comment by kyazdani42** [comment]
I haven't been able to crash the elm parser by extracting the injected bits into files. This might be an issue with neovim itself then ?

**Comment by kyazdani42** [comment]
Closing this one since replacing elm tags with haskell doesn't crash the parser. Although i haven't been able to reproduce the elm crash in elm files.
