### ISSUE TITLE
Markdown link not highlight link with Parentheses

### ISSUE THREAD

**Issue by eeeXun** [MDeiml/tree-sitter-markdown#51]
![image](https://user-images.githubusercontent.com/58657914/180590396-1b208356-9fb6-439c-8c16-fae0d3450b2a.png)

`https://en.wikipedia.org/wiki/Ping_(networking_utility)#ICMP_packet` as the link contain parentheses.It doesn't highlight properly.

**Comment by MDeiml** [comment]
Thanks, fixed!

**Comment by MDeiml** [comment]
Btw to receive this fix (assuming you use neovim) you need to wait a bit until the lockfile.json in the nvim-treesitter repo is updated (happens automatically from time to time). Then you need to update nvim-treesitter and run `:TSUpdate`.

**Comment by eeeXun** [comment]
@MDeiml thx, will check it later!
