### ISSUE TITLE
Invalid link reference definition highlight

### ISSUE THREAD

**Issue by jupblb** [MDeiml/tree-sitter-markdown#52]
**Describe the bug**

**Code example**
```markdown
-   [Link][]
-   [Link2][]

  [Link]: https://google.com
  [Link2]: https://gmail.com
```

**Expected behavior**

Link reference definitions are highlighted as such. Commonmark reference allows up to three spaces of identation for them ([src](https://spec.commonmark.org/0.30/#link-reference-definition)).

**Actual behavior**
![Screenshot 2022-08-04 at 16 38 12](https://user-images.githubusercontent.com/3370617/182874811-1913f16f-8279-4040-a91c-8196e614b95b.png)

**Comment by MDeiml** [comment]
~This seems to be a problem with there not being a newline at the end of the file rather than the indentation. Still a bug :)~

EDIT: It's both

**Comment by jupblb** [comment]
Thanks! :)
