### ISSUE TITLE
wikilinks

### ISSUE THREAD

**Issue by namjul** [MDeiml/tree-sitter-markdown#54]
Maybe this should not be part of tree-sitter-markdown since its not part of [CommonMark Spec](https://spec.commonmark.org/) or [Github flavored markdown](https://github.github.com/gfm/) so just opening up the question of supporting [wikilinks](https://www.mediawiki.org/wiki/Help:Links#Internal_links).

**Comment by MDeiml** [comment]
It could definitely be implemented in a way that it can be conditionally enabled (as an extension). To me it seems like a there would be a few people who would want this.

**Comment by boltlessengineer** [comment]
@MDeiml Just curious, what do you mean by _conditionally enabled_? Does tree-sitter parser can be configured?

**Comment by MDeiml** [comment]
Once the parser is compiled it can't be configured, but I added some code to configure it at compile time (using environment variables). You can see it in the `common/grammar.js`

**Comment by vicrdguez** [comment]
+1 for the feature, ideally given that wikilinks are becoming more and more common, alias text support would make it compatible with multiple tools:

```markdown
[[wikilink]]
[[wikilink|alias]]
```

This could allow mainly for concealing where just `[[alias]]` or `[alias]` is shown

**Comment by mscott99** [comment]
I am trying to enable this feature and am having trouble (new to vim/neovim). How do I set the variable in the readme? Is it in vim.g ?

**Comment by MDeiml** [comment]
This is not really supported that well yet in neovim. See https://github.com/nvim-treesitter/nvim-treesitter/issues/3076. I think the only solution is to build the parser yourself. For this clone the repo, and run the command `EXTENSION_WIKI_LINK=1 npm run build`. This assumes you are using either linux or macos.

Then you have to point nvim-treesitter to this local version. See their documentation on how to do that.

**Comment by MDeiml** [comment]
Closing this as wiki links are now supported (but hidden behind a compilation time flag).

**Comment by ryanpeach** [comment]
@MDeiml how do we enable these in rust bindings?

**Comment by MDeiml** [comment]
Sadly, at the moment this is not possible when using the rust bindings as a normal cargo dependency. You would have to clone this repository locally and run `EXTENSION_WIKI_LINK=1 node scripts/build.js`, then point the other project to this version of the bindings. A system where this is configured through a cargo feature would be better, but this would somehow require the treesitter cli as a build dependency.
