### ISSUE TITLE
Links are not recognised with parenthesis

### ISSUE THREAD

**Issue by ErickChacon** [MDeiml/tree-sitter-markdown#55]
**Describe the bug**
Links in the following format are not recognised `[Link](https://google.com)` at all.

**Code example**
These links are not recognised.
```markdown
[Link](https://google.com)
[Link2](https://gmail.com)
```
But these are recognised.
```
[Link]: https://google.com
[Link2]: https://gmail.com 
```

**Expected behaviour**
I would expect `[Link](https://google.com)`  is recognised as a link.

**Actual behaviour**
It is not recognised as a link, so it is not highlighted.

**Comment by MDeiml** [comment]
It works for me, can you check that you are using the most recent version? There was #51 which was solved recently, maybe that fixed your problem too.

If not, what editor are you using this parser with?

**Comment by ErickChacon** [comment]
It was working for me as well, but after a recent update of `nvim-treesitter` and `tree-sitter-markdown` does not work anymore. I use neovim. Any suggestion to diagnose the problem?

**Comment by MDeiml** [comment]
A few things:
* There is a second grammar, `markdown_inline` which also needs to be kept up to date (thinking about it now this is very likely the problem), so try running `:TSInstall markdown_inline`
* Maybe it's just a problem with your colorscheme?
* Maybe there's a problem with your highlight queryies. What's the output of `:TSEditQuery injections markdown` and `:TSEditQuery highlights markdown_inline`
* If that all doesn't help you could install [tree-sitter playground](https://github.com/nvim-treesitter/playground) and look at the output of `:TSPlaygroundToggle`

**Comment by ErickChacon** [comment]
Hi @MDeiml, thank you so much for your answer. I confirm that the problem was with `markdown_inline`. So `:TSInstall markdown_inline` solved the problem. Thank you so much for your work!
