### ISSUE TITLE
Injection for LaTeX blocks

### ISSUE THREAD

**Issue by brdoney** [MDeiml/tree-sitter-markdown#57]
Although it does not appear to have been added to the GFM spec, GitHub [recently added](https://github.blog/2022-05-19-math-support-in-markdown/) support for LaTeX rendering on their website using `$` and `$$` blocks. It is more formally [outlined here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions). 

Accordingly, It would be amazing if the parser could be extended to detect LaTeX blocks as marked by `$` and `$$` and provide injections for them.

**Comment by danjenson** [comment]
Second this, it would be great because I often write latex in markdown with mathjax

**Comment by MDeiml** [comment]
Good suggestion. This shouldn't be too much of a problem to implement.

**Comment by SichangHe** [comment]
Looking forward to this as well!

**Comment by Entoryvekum** [comment]
Looking forward to the implementation!

**Comment by MDeiml** [comment]
FYI, there is a working PR for this, which should be able to be merged soon #71

**Comment by MDeiml** [comment]
As #71 is closed now, all that is needed is for injection of latex is editor-specific configuration. For people using neovim that means some very small changes in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). I'm happy to help if there are problems.
