### ISSUE TITLE
Incorrect formatting of `tick quoted text`

### ISSUE THREAD

**Issue by David-Else** [MDeiml/tree-sitter-markdown#62]
**Describe the bug**

**Code example**
```markdown
### Search

Search commands all operate on the `d` register by default. Use `"<char>` to operate on a different one.

| Key | Description                                 | Command            |
| --- | ------------------------------------------- | ------------------ |
| `a` | Search for regex pattern                    | `search`           |
| `?` | Search for previous pattern                 | `rsearch`          |
| `n` | Select next search match                    | `search_next`      |
| `N` | Select previous search match                | `search_prev`      |
| `*` | Use current selection as the search pattern | `search_selection` |

```

**Expected behavior**

As GitHub displays above

**Actual behavior**

In Helix (using the latest commit e375ba95ff9a12418f9b9e7c190f549d08b5380a):

![Screenshot from 2022-09-29 09-42-39](https://user-images.githubusercontent.com/12832280/192984469-699fb779-103d-444d-8a90-ef84b5c9bc09.png)

Please also see: https://github.com/helix-editor/helix/issues/3849 , is it enough to update the Helix commit hash or do the queries need modification?

**Comment by Chickenkeeper** [comment]
The main offender seems to be angle brackets in tick quotes. For example that line containing `"<char>` gets formatted correctly as long as there's at most a single angle bracket, or the order of the brackets are reversed, regardless of whatever else is in the quote. If there's at least one < and one > somewhere in the quote, in that order, the highlighting breaks.

Backslashes also prevent the text inside the quote from being highlighted if it isn't immediately followed by a letter or number, but it doesn't seem to affect text around it the way the angle brackets do.

**Comment by MDeiml** [comment]
Stuff that looks like a html tag might "overrule" inline code. That's something that is VERY hard to fix with this parser. I can get into why, but that's a bit more complicated. Though there are some priority values that I can finetune, so getting the simple cases to work might be possible.

Code spans in tables should actually also be highlighted, but that error might be because tables are still buggy.

**Comment by MDeiml** [comment]
I actually managed to fix most of the things that have to do with html tags in code spans. (I just allowed "html tags in code spans", but they are not added as a node to the output). Is there still something that is not workinig?

**Comment by David-Else** [comment]
In the latest master of Helix I get:
![Screenshot from 2022-10-27 11-28-35](https://user-images.githubusercontent.com/12832280/198261403-7fc8d30e-bbbd-44f9-b75b-986c926a0007.png)

So it is partially fixed at the moment.

I assume the latest updates will address the following problematic text?:

```
`/` register by default. Use `"<char>`
```

**Comment by MDeiml** [comment]
Yes, already opened a PR to update the grammar in helix.

**Comment by David-Else** [comment]
Nice one, I will assume all is well and close the issue, thanks for all your hard work on this!
