### ISSUE TITLE
Add the ability to change the background colour of code blocks

### ISSUE THREAD

**Issue by amarz45** [MDeiml/tree-sitter-markdown#64]
I would like to be able to change the background colour of code blocks in Markdown and R Markdown. The colour should span across the entire window, not just the background of the text. Also, the lines for backticks should not be affected by this.

**Comment by MDeiml** [comment]
This can not be implemented in this repo, but depends on the specific editor you're using this parser with. E.g. for neovim you should ask for this feature in `nvim-treesitter`. What editor are you using? Maybe I can point you in the right direction.

**Comment by amarz45** [comment]
I am using Neovim, sorry I forgot to specify.

**Comment by MDeiml** [comment]
Ok thanks. Then you should suggest this feature in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). It should be possible to implement this without changing the parser.
