### ISSUE TITLE
reference links are spellchecked

### ISSUE THREAD

**Issue by gaoDean** [MDeiml/tree-sitter-markdown#67]
**Describe the bug**
The https links are spellchecked, which makes them have red lines under a lot of the text.

**Code example**
```markdown
[2](https://ourworldindata.org/children-not-in-school)
            ^^^^^^^^^^^^^^ <- this is underlined in red
```

**Expected behavior**
links shouldn't be spellchecked

**Actual behavior**
links are spellchecked

**Comment by MDeiml** [comment]
This is not a bug with this parser, but rather the integration into the editor. But I can point you in the direction of the right people to ask. What editor are you using? If it's neovim then this issue belongs to [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

**Comment by gaoDean** [comment]
Ohh, ok thanks so much! I literally started using treesitter yesterday with nvim so I don’t know how most things work.
