### ISSUE TITLE
Code blocks start end end line is concealed

### ISSUE THREAD

**Issue by ghost** [MDeiml/tree-sitter-markdown#68]
Code block start and end line is concealed.

so:
```
```language # not visible has @conceal highlight group
# visible
``` # not visible
```

This is probably a feature. But there should be some way to disable it.

For me it is a problem to edit lines I can't even see. I don't see the point of hiding that text :)

I tried:
vim.api.nvim_set_hl(0, "@conceal", { fg = "#FFFFFF" })
vim.api.nvim_set_hl(0, "@conceal", { bg = "#FFFFFF" })
etc..

But it doesn't work for @conceal.

![Alas, I cannot see](https://user-images.githubusercontent.com/16186848/198032199-8792204b-089b-491b-a301-615444028200.png)

**Comment by MDeiml** [comment]
This is a part of the nvim-treesitter configuration files and not this specific parser, but you can fix it by typing `:TSEditQuery highlight` and removing the line that contains `@conceal` and the thing you don't want to be concealed.

**Comment by ghost** [comment]
Thank you. I reported a bug to treesitter repo.
https://github.com/tree-sitter/tree-sitter/issues/1933
