### ISSUE TITLE
Treesitter is not compatible with spell checking

### ISSUE THREAD

**Issue by 0WN463** [MDeiml/tree-sitter-markdown#70]
I frequently use `:set spell spelllang=en_gb`  to view the spelling mistakes in my markdown file.
However, with treesitter markdown installed, it seems to no longer highlight these mistakes.

I feel this is rather important since markdown usually contains text which needs to be spell checked.

```markdown
iamatypo
```

**Expected behavior**

Using `]s` or `[s` highlight it is a typo.

**Actual behavior**

Using `]s` or `[s` shows no matches.

**Comment by MDeiml** [comment]
I'm not sure how spellchecking is implemented for tree-sitter grammars in neovim. It might need some changes to this grammar. Either way though you should open an issue on [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) first as this is neovim specific and might not have anything to do with this repo.

**Comment by 0WN463** [comment]
Ah right, sorry about that. I thought it was due to the markdown treesitter, but upon further investigation, it was caused by treesitter itself. Thanks a lot
