### ISSUE TITLE
Can't create list item after a list item with a newline and indent

### ISSUE THREAD

**Issue by fisher-j** [MDeiml/tree-sitter-markdown#72]
**Describe the bug**
Line three below should be interpreted as a new list item, but it isn't.

**Code example**
```markdown
1. this works
2. but now we have a long line with
   a line break and indent to match.
3. But then we don't get a new item.
```

**Actual behavior**
![Screenshot 2022-11-16 134111](https://user-images.githubusercontent.com/63136705/202300472-4f51f57e-d0fd-4b17-8e4e-23d6b19e2e08.png)

**Comment by MDeiml** [comment]
Thanks :) Fixed

**Comment by fisher-j** [comment]
Thank you for your continued work on this key piece of software!
