### ISSUE TITLE
List the extra hl groups

### ISSUE THREAD

**Issue by OfekShochat** [MDeiml/tree-sitter-markdown#73]
I'm using the monokai colorscheme, and it doesn't support the hl groups you use. Can you list the (probably) needed extra hl groups so that other colorschemes would know which to add? All or the ones you think are nonstandard for other programming languages. I just don't know where to look really.
Thanks!

**Comment by MDeiml** [comment]
Highlight groups for tree-sitter were recently renamed, so maybe they just weren't updated properly for this theme. You can see all highlight groups with `:h treesitter-highlight-groups`. They are standardized across all languages, so no extra work for markdown should be necessary.

If you are really just interested in the highlight groups that this parser is using, you can look which captures (the identifiers that start with `@`) are used [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown/highlights.scm) and [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown_inline/highlights.scm).

**Comment by OfekShochat** [comment]
ohh, this would make sense! I had issues all week with highlighting!

**Comment by MDeiml** [comment]
Closing this, as problem seems to be solved
