### ISSUE TITLE
Erroneous concealing of to-do status brackets

### ISSUE THREAD

**Issue by aleksey-rowan** [MDeiml/tree-sitter-markdown#78]
**Describe the bug**

To-do status brackets are concealed for any other symbol apart from `x`:

<img alt="Screenshot 2023-01-09 at 20 21 16@2x" width="246" src="https://user-images.githubusercontent.com/1285419/211447375-e4c5c03b-3af2-4f32-9eff-b4e475967c18.png"> <img alt="Screenshot 2023-01-09 at 20 21 29@2x" width="221" src="https://user-images.githubusercontent.com/1285419/211447389-2d1a78fd-f01f-4c38-baeb-df47574eb3c8.png">

> Originally posted by @piersolenski in https://github.com/jakewvincent/mkdnflow.nvim/pull/110#issuecomment-1376635685

**Expected behavior**

To-do status bracket are never concealed.

**Comment by MDeiml** [comment]
This is not a bug with this parser, but with how it is configured [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). This parser does not define any concealing.

**Comment by aleksey-rowan** [comment]
Got it, thank you for clarification. I'll open an issue there.
