### ISSUE TITLE
`latex` inline highlighting doesn't work properly in markdown file 

### ISSUE THREAD

**Issue by schardev** [MDeiml/tree-sitter-markdown#83]
If a markdown file has a heading, then it doesn't highlight inline latex line. Probably due to incorrect nodes been parsed(?).

Example Snippet:

```markdown
## Heading
$\frac{{x}{y}^m}$
```

see https://github.com/nvim-treesitter/nvim-treesitter/issues/4349 for more info

**Comment by clason** [comment]
Turns out this is an issue with Neovim injections, which has just been fixed.
