### ISSUE TITLE
Migrate scanner.cc to C

### ISSUE THREAD

**Issue by lewis6991** [MDeiml/tree-sitter-markdown#84]
Hey, we are thinking about bundling this parser into Neovim for v0.9, however one of the concerns is raising our build requirements to include C++. (https://github.com/neovim/neovim/pull/22458)

I've had a play with the markdown scanner.cc and I think it will be fairly straightforward to port this to C. To replace `vector` I think we could just include https://github.com/neovim/neovim/blob/master/src/klib/kvec.h.

Would this be something you would be open too?

**Comment by MDeiml** [comment]
Of course. Totally on board.
