### ISSUE TITLE
Support ```js and ```ts as aliases for ```javascript and ```typescript

### ISSUE THREAD

**Issue by CallumHoward** [MDeiml/tree-sitter-markdown#94]
Hopefully this might be the right level at which to solve this:

ghfmd seems to support `js`/`ts` as an abbreviation for `javascript`/`typescript`.

---

Example:

```ts
const a: string = "some highlighted ts code";
```

``` js
const a = "some highlighted js code";
```

---

In Neovim v0.9 with latest treesitter and parsers installed:
<img width="487" alt="Screenshot 2023-04-10 at 4 18 44 pm" src="https://user-images.githubusercontent.com/7144420/230839698-b6807290-e5fd-4d2d-b422-9b5cf0689111.png">
<img width="449" alt="Screenshot 2023-04-10 at 4 21 21 pm" src="https://user-images.githubusercontent.com/7144420/230839878-44c8e514-f8c4-4ac9-9473-339337015d46.png">

Would it be possible to add aliases so that `ts` and `js` in the code block language specifier may work?

**Comment by MDeiml** [comment]
That's a problem with neovim. The parser just tells neovim that the language is "ts" and neovim needs to figure out what parser to use. Maybe this functionality is already implemented, but I didn't find anything about it immediately. You should probably ask in https://github.com/nvim-treesitter/nvim-treesitter

**Comment by clason** [comment]
Yes, that should be implemented, and works for me: 

<img width="776" alt="Screenshot 2023-05-13 at 20 25 35" src="https://github.com/MDeiml/tree-sitter-markdown/assets/2361214/0dee6e0b-5030-4c66-9c97-2c358b65dfaf">

Make sure your nvim-treesitter is fully updated.

(PR adding more common aliases to see https://github.com/nvim-treesitter/nvim-treesitter/blob/680807fa6a482c639119098bc48ca3831c66db13/lua/nvim-treesitter/query_predicates.lua#L10-L16 welcome).

**Comment by MDeiml** [comment]
Closing, as this is related to neovim and not this parser.
