### ISSUE TITLE
Some additional indication that markdown links are links while concealed

### ISSUE THREAD

**Issue by trev-dev** [MDeiml/tree-sitter-markdown#98]
When conceal is on, I can't tell Markdown bullet items from bullet items that are also links.  It would be super cool if links also had an underline in the link text or something.

**Comment by trev-dev** [comment]
99% this is just my theme sucking at `@text.reference` highlighting.  Thanks anyway

**Comment by MDeiml** [comment]
Sorry for not responding, were you able to solve your problem?

**Comment by trev-dev** [comment]
> Sorry for not responding, were you able to solve your problem?

Yep! I set the highlight myself and made link titles more distinct
